---
- name: Ensure packages exists
  yum:
    name: "{{ update_packages }}"
    state: present

- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip
    state: latest
  ignore_errors: true

- pip:
    name: pyopenssl

- sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: yes
    state: "{{ state }}"

- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: "{{ state }}"

- name: create wildfly dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: 0755
  with_items:
    - "{{ wildfly_dir }}"
    - "{{ wildfly_conf }}"
    - "{{ wildfly_certs }}"
    - "{{ wildfly_war }}"

