---
- name: Ensure packages exists
  yum:
    name: "{{ update_packages }}"
    state: present

- name: Update to latest
  when: update.enabled|bool
  yum:
    name: '*'
    state: latest
    exclude: "{{ update.exclude|join(',') }}"

- name: install epel-release
  yum:
    name: epel-release
    state: latest
