###############
# Common Vars #
###############
basepackages:
  - parted
  - htop
  - ntp
  - python
  - tcpdump
  - wget
  - openssl
  - curl

docker_user: root
docker_dir: /opt/docker
docker_storage_path: /mnt/data
syncserver_fqdn: syncserver.ruv.de

ansible_connection: ssh
ansible_ssh_user: vagrant
debug_enabled_default: true
default_update_password: always 
default_shell: /bin/bash


###########
# WILDFLY #
###########
wildfly_dir: /etc/wildfly
wildfly_conf: /etc/wildfly/conf
wildfly_certs: /etc/wildfly/certs
wildfly_war: /etc/wildfly/war
wildfly_cli: /etc/wildfly/cli
wildfly_vg: wildfly_vg
wildfly_lv: wildfly_lv
wildfly_device: /dev/mapper/wildfly_lv
wildfly_db_host: postgres04.dev.cloud.ruv.de
wildfly_db_port: '6432'
wildfly_db: d_wildfly
wildfly_db_user: r_wildfly
wildfly_db_pass: e36a1cdb10ee7a41fbb7d943a9bab6dd
wildfly_user: admin
wildfly_pass: E13itbv++
wildfly_version: v0.2
wildfly_container_name: wildflyruv
wildfly_container_version: latest 
wildfly_container_location: jboss/wildfly

########
# USER #
########

users:
  - username: testuser101
    password: $6$/y5RGZnFaD3f$96xVdOAnldEtSxivDY02h.DwPTrJgGQl8/MTRRrFAwKTYbFymeKH/1Rxd3k.RQfpgebM6amLK3xAaycybdc.60
    update_password: on_create
    comment: Test User 100
    shell: /bin/bash
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8crAHG/a9QBD4zO0ZHIjdRXy+ySKviXVCMIJ3/NMIAAzDyIsPKToUJmIApHHHF1/hBllqzBSkPEMwgFbXjyqTeVPHF8V0iq41n0kgbulJG testuser101@server1
      ssh-rsa AAAA.... testuser101@server2
    exclusive_ssh_key: yes
    use_sudo: no
    use_sudo_nopass: no
    user_state: present
    servers:
      - worker

  - username: testuser102
    password: $6$F/KXFzMa$ZIDqtYtM6sOC3UmRntVsTcy1rnsvw.6tBquOhX7Sb26jxskXpve8l6DYsQyI1FT8N5I5cL0YkzW7bLbSCMtUw1
    update_password: always
    comment: Test User 101
    groups: testcommon, testgroup102db
    shell: /bin/sh
    use_sudo: yes
    user_state: present
    servers:
      - worker

  - username: testuser102
    password: $6$F/KXFzMa$ZIDqtYtM6sOC3UmRntVsTcy1rnsvw.6tBquOhX7Sb26jxskXpve8l6DYsQyI1FT8N5I5cL0YkzW7bLbSCMtUw1
    update_password: always
    comment: Test User 101
    groups: testcommon, testgroup102db
    shell: /bin/sh
    user_state: present
    servers:
      - worker

  - username: testuser103
    password: $6$wBxBAqRmG6O$gPbg9hYShkuIe3YKMFujwiKsPKZHNFwoK4yCyTOlploljz53YSoPdCn9P5k8Qm0z062Q.8hvJ6DnnQQjwtrnS0
    user_state: present
    servers:
      - worker

  - username: testuser104
    ssh_key: ssh-rsa AAAB.... test103@server
    exclusive_ssh_key: no
    use_sudo: no
    user_state: present
    servers:
      - worker

  - username: testuser105
    uid: 1099
    password: $6$XEnyI5UYSw$Rlc6tXtECtqdJ3uFitrbBlec1/8Fx2obfgFST419ntJqaX8sfPQ9xR7vj7dGhQsfX8zcSX3tumzR7/vwlIH6p/
    ssh_key: ssh-rsa AAAB.... test107@server
    use_sudo: no
    user_state: lock
    servers:
      - worker

