###############
# Common Vars #
###############
basepackages:
  - parted
  - htop
  - ntp
  - python
  - tcpdump
  - wget
  - openssl
  - curl

docker_user: root
docker_dir: /opt/docker
docker_storage_path: /mnt/data
syncserver_fqdn: syncserver.ruv.de

ansible_connection: ssh
ansible_ssh_user: vagrant



###########
# WILDFLY #
###########
wildfly_dir: /etc/wildfly
wildfly_conf: /etc/wildfly/conf
wildfly_certs: /etc/wildfly/certs
wildfly_war: /etc/wildfly/war
wildfly_cli: /etc/wildfly/cli
wildfly_vg: wildfly_vg
wildfly_lv: wildfly_lv
wildfly_device: /dev/mapper/wildfly_lv
wildfly_db_host: postgres04.dev.cloud.ruv.de
wildfly_db_port: '6432'
wildfly_db: d_wildfly
wildfly_db_user: r_wildfly
wildfly_db_pass: e36a1cdb10ee7a41fbb7d943a9bab6dd
wildfly_user: admin
wildfly_pass: E13itbv++
wildfly_version: v0.2
wildfly_container_name: wildflyruv
wildfly_container_version: latest 
wildfly_container_location: jboss/wildfly

