---
- name: template Dockerfile
  template:
    src: "{{ item }}"
    dest: "{{ wildfly_dir }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - Dockerfile
    - docker-entrypoint.sh

- name: build wildfly container
  docker_image:
    build:
      path: "{{ wildfly_dir }}"
    tag: "{{ wildfly_version }}"
    pull: true
    source: build
    name: "{{ wildfly_container_name }}"

- name: running wildfly container
  docker_container:
    name: "{{ wildfly_container_name }}"
    image: "{{ wildfly_container_name }}:{{ wildfly_version }}"
    state: started
    hostname: "{{ ansible_ssh_host }}"
    log_driver: journald
    recreate: yes
    restart_policy: unless-stopped
    ports:
      - 7600:7600
      - 8080:8080
      - 8443:8443
      - 9090:9090
      - 45700:45700
      - 57600:57600
    env:
      #DB_PORT: "{{ wildfly_db_port }}"
      #DB_VENDOR: postgres
      DB_ADDR: "{{ wildfly_db_host }}"
      DB_DATABASE: "{{ wildfly_db }}"
      DB_USER: "{{ wildfly_db_user }}"
      #DB_SCHEMA: public
      DB_PASSWORD: "{{ wildfly_db_pass }}"
      KEYCLOAK_USER: "{{ wildfly_user }}"
      KEYCLOAK_PASSWORD: "{{ wildfly_pass }}"
      PROXY_ADDRESS_FORWARDING: "true"
      HOST_ADDR: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_EXTERNAL_IP: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    volumes:
      - /etc/wildfly/certs:/etc/x509/https

