---
- name: template Dockerfile
  template:
    src: "{{ item }}"
    dest: "{{ wildfly_dir }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - Dockerfile
    - docker-entrypoint.sh

- name: build wildfly container
  docker_image:
    build:
      path: "{{ wildfly_dir }}"
    tag: "{{ wildfly_version }}"
    #build.pull: yes
    source: build
    name: "{{ wildfly_container_name }}"


- name: running wildfly container
  docker_container:
    name: "{{ wildfly_container_name }}"
    image: "{{ wildfly_container_name }}:{{ wildfly_version }}" 
    state: started
    hostname: "{{ ansible_ssh_host }}"
    log_driver: journald
    recreate: yes
    restart_policy: unless-stopped
    ports:
      - 8080:8080
      - 9990:9990
    env:
      PROXY_ADDRESS_FORWARDING: "true"
      HOST_ADDR: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    volumes:
      - /etc/wildfly/certs:/etc/x509/https
      - /etc/wildfly/war:/opt/jboss/wildfly/standalone/deployments/

