---
- name: WildFly | Install
  include: install.yml
  tags:
    - install

- name: WildFly | Configure
  include: configure.yml
  tags:
    - configure

- name: WildFly | Service
  include: service.yml
  tags:
    - service
