- name: build keycloak container
  docker_image:
    build:
      path: "{{ keyclo_dir }}"
    tag: "{{ keyclo_version }}"
    pull: true
    source: build
    name: "{{ keyclo_container_name }}"

- name: running keycload container
  docker_container:
    name: "{{ keyclo_container_name }}"
    image: "{{ keyclo_container_name }}:{{ keyclo_version }}"
    state: started
    hostname: "{{ ansible_ssh_host }}"
    log_driver: journald
    recreate: yes
    restart_policy: unless-stopped
    ports:
      - 7600:7600
      - 8080:8080
      - 8443:8443
      - 9090:9090
      - 45700:45700
      - 57600:57600
    env:
      #DB_PORT: "{{ keyclo_db_port }}"
      #DB_VENDOR: postgres
      DB_ADDR: "{{ keyclo_db_host }}"
      DB_DATABASE: "{{ keyclo_db }}"
      DB_USER: "{{ keyclo_db_user }}"
      #DB_SCHEMA: public
      DB_PASSWORD: "{{ keyclo_db_pass }}"
      KEYCLOAK_USER: "{{ keyclo_user }}"
      KEYCLOAK_PASSWORD: "{{ keyclo_pass }}"
      PROXY_ADDRESS_FORWARDING: "true"
      HOST_ADDR: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_EXTERNAL_IP: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    volumes:
      - /etc/keycloak/certs:/etc/x509/https

